version: '3.7'

services:
  app:
    image: app:${SERVICE_IMAGE_TAG}
    container_name: app
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - SERVER_PORT
      - API_BASE_PATH
      - MAX_FILE_SIZE
      - MONGODB_HOST
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - GRIDFS_BUCKET_NAME
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  mongodb:
    image: bitnami/mongodb:${MONGO_IMAGE_TAG}
    container_name: mongodb
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE
      - MONGODB_ROOT_PASSWORD
    volumes:
      - ./data/mongodb-data:/bitnami/mongodb:Z
    ports:
      - 27017:27017

  redis:
    image: bitnami/redis:${REDIS_IMAGE_TAG}
    container_name: redis
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - REDIS_PASSWORD
    volumes:
      - ./data/redis-data:/bitnami/redis/data:Z
    ports:
      - 6379:6379